// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYpyYRbqNHXKmy2frGj6qupKTxu-x08B0',
    appId: '1:19665962614:web:502b307f65ce281c714157',
    messagingSenderId: '19665962614',
    projectId: 'recipe-fe94e',
    authDomain: 'recipe-fe94e.firebaseapp.com',
    storageBucket: 'recipe-fe94e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWWSfXmEz-gVCAcz4uRdGEXnP14dMv78',
    appId: '1:19665962614:android:e54be5586a0362be714157',
    messagingSenderId: '19665962614',
    projectId: 'recipe-fe94e',
    storageBucket: 'recipe-fe94e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDGeHcS1B-Rg7JAwmK_wqo2PjB9TmS2s',
    appId: '1:19665962614:ios:8991892ed573e837714157',
    messagingSenderId: '19665962614',
    projectId: 'recipe-fe94e',
    storageBucket: 'recipe-fe94e.appspot.com',
    iosBundleId: 'com.example.sqliteFlutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDGeHcS1B-Rg7JAwmK_wqo2PjB9TmS2s',
    appId: '1:19665962614:ios:8991892ed573e837714157',
    messagingSenderId: '19665962614',
    projectId: 'recipe-fe94e',
    storageBucket: 'recipe-fe94e.appspot.com',
    iosBundleId: 'com.example.sqliteFlutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYpyYRbqNHXKmy2frGj6qupKTxu-x08B0',
    appId: '1:19665962614:web:a8ef9c27eae64fa5714157',
    messagingSenderId: '19665962614',
    projectId: 'recipe-fe94e',
    authDomain: 'recipe-fe94e.firebaseapp.com',
    storageBucket: 'recipe-fe94e.appspot.com',
  );
}
